apiVersion: v1
data:
  settings: |-
    {
      "DASHBOARD_FORCE_IFRAME": true
    }
  links: |-
    {
        "menuLinks": [
            {
                "icon": "book",
                "link": "/jupyter/",
                "text": "Notebooks",
                "type": "item"
            },
            {
                "icon": "assessment",
                "link": "/tensorboards/",
                "text": "TensorBoards",
                "type": "item"
            },
            {
                "icon": "device:storage",
                "link": "/volumes/",
                "text": "Volumes",
                "type": "item"
            },
            {
                "icon": "kubeflow:katib",
                "link": "/katib/",
                "text": "Katib Experiments",
                "type": "item"
            },
            {
                "type": "item",
                "link": "/kserve-endpoints/",
                "text": "KServe Endpoints",
                "icon": "kubeflow:models"
            },
            {
                "icon": "kubeflow:pipeline-centered",
                "items": [
                    {
                        "link": "/pipeline/#/pipelines",
                        "text": "Pipelines",
                        "type": "item"
                    },
                    {
                        "link": "/pipeline/#/experiments",
                        "text": "Experiments",
                        "type": "item"
                    },
                    {
                        "link": "/pipeline/#/runs",
                        "text": "Runs",
                        "type": "item"
                    },
                    {
                        "link": "/pipeline/#/recurringruns",
                        "text": "Recurring Runs",
                        "type": "item"
                    },
                    {
                        "link": "/pipeline/#/artifacts",
                        "text": "Artifacts",
                        "type": "item"
                    },
                    {
                        "link": "/pipeline/#/executions",
                        "text": "Executions",
                        "type": "item"
                    }
                ],
                "text": "Pipelines",
                "type": "section"
            }
        ],
        "externalLinks": [
            {
                "type": "item",
                "link": "http://localhost:8083",
                "text": "mlflow",
                "icon": "av:loop"
            },
            {
                "type": "item",
                "link": "http://localhost:8081",
                "text": "Aim",
                "icon": "editor:multiline-chart"
            },
            {
                "type": "item",
                "link": "http://localhost:8082",
                "text": "lakeFS",
                "icon": "icons:cloud"
            }
        ],
        "documentationItems": [
            {
                "desc": "The AI Streamliner GitHub repository contains the source code and documentation for the AI Streamliner project.",
                "link": "https://github.com/ArdentMC/ai-streamliner?tab=readme-ov-file#ai-streamliner",
                "text": "AI Streamliner"
            }
        ],
        "quickLinks": [
            {
                "desc": "Kubeflow Notebooks",
                "link": "/jupyter/new",
                "text": "Create a new Notebook"
            },
            {
                "desc": "Kubeflow Pipelines",
                "link": "/pipeline/#/pipelines",
                "text": "Upload a Pipeline"
            },
            {
                "desc": "Pipelines",
                "link": "/pipeline/#/runs",
                "text": "View Pipeline Runs"
            }
        ]
    }
kind: ConfigMap
metadata:
  name: centraldashboard-config
  namespace: kubeflow