apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aimstack
  name: aimstack
  namespace: aimstack
spec:
  selector:
    matchLabels:
      app: aimstack
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aimstack
    spec:
      containers:
        - name: ui
          image: aimstack/aim:latest
          ports:
            - containerPort: 43800
              protocol: TCP
              name: ui
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi